# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    clean: true
    fetchTags: false
  - task: NodeTool@0
    displayName: Use Node x.x
    inputs:
      versionSpec: 18.x
      checkLatest: true
  - task: Npm@1
    displayName: npm install
    inputs:
      command: custom
      verbose: false
      customCommand: install --force
  - task: Npm@1
    displayName: npm build
    inputs:
      command: custom
      verbose: false
      customCommand: run build
  - task: Npm@1
    displayName: npm export
    inputs:
      command: custom
      verbose: false
      customCommand: run export
  - task: ArchiveFiles@2
    displayName: Archive files
    inputs:
      rootFolderOrFile: $(System.DefaultWorkingDirectory)/out
      includeRootFolder: false
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'
